version: '3.8'

services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    profiles: ["dev"]

  api:
    container_name: dataset_scrapper
    command: python3.9 manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    expose:
      - "8000"
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    env_file:
      - django_app/.env
    environment:
      - WRITE_TO_KAFKA=True   # use ${WRITE_TO_KAFKA} to get value from .env
    stdin_open: true
    volumes:
      - datasets:/api/datasets

volumes:
  datasets:
